### ISSUE TITLE
Unable to register

### ISSUE THREAD

**Issue by syedautherabbas** [oslabs-beta/shepherd#54]
**Describe the bug**
Unable to register a new account as the registration fails at "Add Shepherd CloudFormation stack to AWS" step. 

**To Reproduce**
1. Go to 'Register'
2. Click on 'Add Shepherd CloudFormation stack to AWS'
3. Login with AWS credentials
4. Encounter this below error
![image](https://user-images.githubusercontent.com/12937522/146626090-806cb7b6-2ee2-4b4e-9ed5-832aed6baea6.png)

**Expected behavior**
Should have allowed to register

**Screenshots**
![image](https://user-images.githubusercontent.com/12937522/146626102-0db7f1ee-5b1d-47be-a2e9-3f6f7a228ef8.png)

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser Chrome
 - Version no tags yet

**Comment by AndrewNguyenn** [comment]
Solved
